import Head from "next/head";
import Link from "next/link";

import Header from "../components/Header";
import Footer from "../components/Footer";
import Maker from "../components/Maker";

import about from "../styles/About.module.css";

export default function About() {
  return (
    <>
      <Head>
        <title>Not Boring Design System Names</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <Header />
        <main>
            <div className={about.hero}>
              <h1 className="heading-1 text-high-emphasis">Built by Specify<span className={about.icon + " " + about.specify}></span><br/>Powered by OpenAI GPT-3<span className={about.icon + " " + about.openai}></span>and Vercel Edge Functions<span className={about.icon + " " + about.vercel}></span>.</h1>
            </div>
            <div className={about.content}>
              <div className={about.story}>
                <div className={about.storyPart}>
                  <h2 className="body-2-l text-low-emphasis">Initial inspiration</h2>
                  <p className="body-1-s text-medium-emphasis">During our 2023 Winter Retreat in January, during our hackathon day, we think about how AGI can help teams working with/on design systems. A lot of topics were mentioned, and we thought about <Link className="text-info" href="https://designtitles.com/">Design Titles ↗︎</Link>, a playful website created by Xtian Miller and Boris Crowther where you can generate job names for designers.</p>
                  <p className="body-1-s text-medium-emphasis">We loved this idea of generating names, and we know from experience naming stuff, whether we talk about tokens, components, or even worse — your layers, can sometimes be tricky. So we chose to build a tool that provides ideas for teams looking for a name for their design systems.</p>
                </div>
                <div className={about.storyPart}>
                  <h2 className="body-2-l text-low-emphasis">Proof of Concept</h2>
                  <p className="body-1-s text-medium-emphasis">Very often, design systems tend to be named &#123;companyName&#124; UI, &#123;companyName&#124; Design System, &#123;companyName&#124; DLS. While this is totally fine, we were wondering if GPT-3 could generate appropriate names based on the company name, its brand characteristics and its space. In addition, we wanted a name that could make sense for every company and its design system.</p>
                  <p className="body-1-s text-medium-emphasis">After playing a bit with ChatGPT to see if that could be interesting, we created a proof of concept resulting in a simple Next JS app with three input fields, a button, and a result displayed in a way too big font size, set in Inter (of course).</p>
                </div>
                <div className={about.storyPart}>
                  <h2 className="body-2-l text-low-emphasis">Final product</h2>
                  <p className="body-1-s text-medium-emphasis">During our cooldown week of April, Yann-Edern took the initiative to transform this POC into something that can be shared on the Internets. He also made it more on-brand, improved the prompt sent to GPT-3, and leveraged Vercel Edge Functions, thanks to <Link className="text-info" href="https://vercel.com/blog/gpt-3-app-next-js-vercel-edge-functions">this brilliant article ↗︎</Link> from Hassan El Mghari.</p>
                </div>
              </div>              
              <div className={about.informations}>
                <div className={about.information}>
                  <p className="body-2-l text-low-emphasis">Makers</p>
                  <div className={about.makers}>
                    <Maker name="Yann-Edern Gillet" role="Product Designer" link="" path="yann.jpg" />
                    <Maker name="Mohamed Khalil Elloumi" role="Back-End Engineer" link="" path="khalil.jpg" />
                    <Maker name="Maud Miguet" role="Product Manager" link="" path="maud.jpg" />
                    <Maker name="Alexis Bonnefon" role="People Manager" link="" path="alexis.jpg" />
                  </div>
                </div>
                <div className={about.information}>
                  <div className={about.stackTitle}>
                    <p className="body-2-l text-low-emphasis">Stack</p>
                    <Link className="body-2-s text-info" href="https://github.com/yannglt/not-boring-ds-names">View code ↗︎</Link>
                  </div>
                  <div className={about.stackList}>
                    <div className={about.stackItem}>
                      <p className="body-2-s text-medium-emphasis">Framework</p>
                      <p className="body-2-l text-high-emphasis">Next JS</p>
                    </div>
                    <div className={about.stackItem}>
                      <p className="body-2-s text-medium-emphasis">Animations</p>
                      <p className="body-2-l text-high-emphasis">Framer Motion + Lottie</p>
                    </div>
                    <div className={about.stackItem}>
                      <p className="body-2-s text-medium-emphasis">AGI Model</p>
                      <p className="body-2-l text-high-emphasis">OpenAI GPT-3.5 Turbo</p>
                    </div>
                    <div className={about.stackItem}>
                      <p className="body-2-s text-medium-emphasis">Deployment</p>
                      <p className="body-2-l text-high-emphasis">Vercel</p>
                    </div>
                  </div>
                </div>
                <div className={about.information}>
                  <p className="body-2-l text-low-emphasis">About Specify</p>
                  <div className={about.logo}></div>
                  <p className="body-2-s text-medium-emphasis">Specify is a design system infrastructure for modern teams. With Specify, product teams release better experiences faster while staying in-line with their company standards.</p>
                </div>
              </div>
            </div>
        </main>
        <Footer />
      </div>
    </>
  );
}