import Head from 'next/head'
import Image from 'next/image'
import { useRef, useState } from "react";
import Header from "../components/Header";
import hero from "../styles/Hero.module.css";
import form from "../styles/Form.module.css";

export default function Home() {
  const [loading, setLoading] = useState(false);
  const [companyName, setCompanyName] = useState("");
  const [brandCharacteristics, setBrandCharacteristics] = useState("");
  const [space, setSpace] = useState("");
  const [generatedName, setGeneratedName] = useState("");

  const prompt = `
    A design system is a collection of reusable design components, guidelines, and standards that are used to create consistent and cohesive user interfaces across different products or platforms. It helps designers and developers work more efficiently and ensures a consistent brand identity and user experience. 
    
    Suggest me a name for the design system of ${companyName}. 
    
    The name should :
    - be one word only and different that the brand name itself;
    - fits in the ${space} industry, reflects ${brandCharacteristics} brand characteristics. 
    - not contains the term "x", "design system" or "design" in it.
    
    Here are some examples of some well-know design systems: Material (Google), Fluent (Microsoft), Carbon (IBM), Polaris (Shopify), and Spectrum (Adobe).
  `;

  const generateName = async (e: any) => {
    e.preventDefault();
    setGeneratedName("");
    setLoading(true);
    const response = await fetch("/api/generate", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        prompt,
      }),
    });

    if (!response.ok) {
      throw new Error(response.statusText);
    }

    const data = response.body;
    if (!data) {
      return;
    }

    const reader = data.getReader();
    const decoder = new TextDecoder();
    let done = false;

    while (!done) {
      const { value, done: doneReading } = await reader.read();
      done = doneReading;
      const chunkValue = decoder.decode(value);
      setGeneratedName((prev) => prev + chunkValue);
    }
    setLoading(false);
  };

  return (
    <>
      <Head>
        <title>Not Boring Design System Names</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <div className={hero.hero}>
          <p className="heading-1 text-high-emphasis">Empower your design system<img src="/images/designSystem.svg" className={hero.heroIcon + " " + hero.designSystem}/>with a memorable name<img src="/images/name.svg" className={hero.heroIcon + " " + hero.name}/>that conveys emotions<img src="/images/emotions.svg" className={hero.heroIcon + " " + hero.emotions}/>, and extends your brand characteristics<img src="/images/brandCharacteristics.svg" className={hero.heroIcon + " " + hero.brandCharacteristics}/>.</p>
          <p className="body-1-s text-low-emphasis">Your design system is the backbone of your brand's visual identity, but a great name can take it to the next level. With the power of AI, we'll help you generate a name that captures your brand's unique characteristics, industry, and personality.</p>
        </div>
        <div className={form.container}>
          <form className={form.form} onSubmit={generateName}>
            <div className={form.group}>
              <label htmlFor="companyName" className="body-2-l text-high-emphasis">Company name</label>
              <input type="text" id="companyName" name="companyName" className="body-2-m text-medium-emphasis" placeholder="NASA" onChange={(event) => setCompanyName(event.target.value)} />
            </div>
            <div className={form.group}>
              <label htmlFor="brandCharacteristics" className="body-2-l text-high-emphasis">Brand characteristics</label>
              <input type="select" id="brandCharacteristics" name="brandCharacteristics" className="body-2-m text-medium-emphasis" placeholder="Creative" onChange={(event) => setBrandCharacteristics(event.target.value)} />
            </div>
            <div className={form.group}>
              <label htmlFor="space" className="body-2-l text-high-emphasis">Space</label>
              <select name="space" id="space" className="body-2-m text-medium-emphasis" onChange={(event) => setSpace(event.target.value)}>
                <option value="automotive">Automotive</option>
                <option value="banking">Banking</option>
                <option value="construction">Construction</option>
                <option value="education">Education</option>
                <option value="energy">Energy</option>
                <option value="entertainment">Entertainment</option>
                <option value="finance">Finance</option>
                <option value="food">Food</option>
                <option value="healthcare">Healthcare</option>
                <option value="hospitality">Hospitality</option>
                <option value="insurance">Insurance</option>
                <option value="manufacturing">Manufacturing</option>
                <option value="media">Media</option>
                <option value="real-estate">Real Estate</option>
                <option value="retail">Retail</option>
                <option value="technology">Technology</option>
                <option value="telecommunications">Telecommunications</option>
                <option value="transportation">Transportation</option>
                <option value="travel">Travel</option>
                <option value="utilities">Utilities</option>
              </select>
            </div>
            <button className="button-primary" type="submit" disabled={loading}>Generate a name</button>
          </form>
          <div className={form.result}>
            { generatedName && !loading 
              ? <p className="display-1 text-high-emphasis text-result">{generatedName.replace(".", "")} <br/>Design System</p>
              : <p className="display-1 text-low-emphasis text-disabled">Your design system name</p>            
            }

            {/* { result             
              ? <p className="body-emphasis text-low-emphasis">{result.explanation}</p>
              : <p className="body-emphasis text-low-emphasis">You'll find the perfect description for your design system</p>           
            } */}
          </div>
        </div>
        {/* <button onClick={(e) => generateName(e)}>Generate your name &rarr;</button>
        { loading ? <p>Loading...</p> : <p>{generatedName}</p> } */}
      </main>
    </>
  )
}
